databases:
  - name: hillsclinic-db
    databaseName: hillsclinic
    user: hillsclinic
    plan: free

services:
  - type: web
    name: hillsclinic
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn hillsclinic.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hillsclinic-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://hillsclinic.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
