databases:
  - name: hillsclinic-db
    databaseName: hillsclinic
    user: hillsclinic
    plan: free

services:
  - type: web
    name: hillsclinic
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py makemigrations --no-input && python manage.py migrate && python manage.py set_site_domain && python manage.py setup_homepage && python manage.py setup_doctors && python manage.py create_superuser_if_not_exists"
    startCommand: "gunicorn hillsclinic.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hillsclinic-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://hillsclinic.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: SITE_DOMAIN
        value: "hillsclinic.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      # Email settings (Gmail SMTP)
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "darkiegaming21@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "tofp ahnv bmwg bmcd"
      - key: DEFAULT_FROM_EMAIL
        value: "Hills Clinic <darkiegaming21@gmail.com>"
